#!/usr/bin/env bash
# transfers a file from our client to a server

PATH_TO_FILE=$1
IP_ADDR=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4  

if [[ $# -lt 4 ]];
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -r -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP_ADDR":~/"$PATH_TO_FILE"
fi
