#!/usr/bin/env bash
# Installs NGINX with all bells and whistles

apt-get -y update
apt-get install -y nginx
echo Holberton School | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
