#!/usr/bin/env bash
# Add redirection

LINE="\tlocation /redirect_me {\n\t\treturn 301 https://www.bing.com/;\n\t}"
FILE="/etc/nginx/sites-available/default"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "/server {/i $LINE" "$FILE"
sudo service nginx restart
