#!/usr/bin/env bash
# Add redirection

LINE="\tlocation /redirect_me {\n\t\treturn 301 https://www.bing.com/;\n\t}"
FILE="/etc/nginx/sites-available/default"

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i "/server_name _;/a $LINE" "$FILE"
service nginx restart
