#!/usr/bin/env bash
# prints 'Holberton School' 10 times but prints 'Hi' after 9th iteration

while (( i < 10 ))
do
	if (( i == 9 ))
	then
		echo "Hi"
    	fi
	echo "Holberton School"
	(( i += 1 ))
done
