#!/usr/bin/env bash
# prints the time for 12 hours and 59 minutes

i=0
while (( i <= 12 ))
do
	echo "Hour: $i"
	MINUTE=1
	while (( MIN <= 59 ))
	do
		echo "$MINUTE"
		(( MINUTE += 1 ))
	done
(( i += 1 ))
done
